# Generated by Django 3.2.3 on 2021-05-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_remove_pelcon_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileformupload',
            name='owner',
            field=models.CharField(default='un know', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileformupload',
            name='file',
            field=models.FileField(upload_to='document/'),
        ),
    ]
