# Generated by Django 3.2.3 on 2021-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20210525_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelcon',
            name='path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelcon',
            name='pdf',
            field=models.FileField(upload_to='store/pdfs/<django.db.models.fields.CharField>'),
        ),
    ]
