# Generated by Django 3.2.3 on 2021-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_alter_pelcon_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelcon',
            name='path',
        ),
        migrations.AlterField(
            model_name='pelcon',
            name='pdf',
            field=models.FileField(upload_to='store/pdfs'),
        ),
    ]
